AU_SOURCE_DIR_RELATIVE = "../../../code-clones/Antistasi-Ultimate-Community/A3-Antistasi-Ultimate"
GRAD_MEH_DATA_DIR_RELATIVE = "../../../gruppe-adler/meh-data"
INTERMEDIATE_DATA_DIR_RELATIVE = "../working_data"
MARKDOWN_OUTPUT_FILE_RELATIVE = "../docs/index.md"
