AU_SOURCE_DIR_RELATIVE = "../../../SilenceIsFatto/A3-Antistasi-Ultimate/A3A/addons/maps"
INTERMEDIATE_DATA_DIR_RELATIVE = "../data"
GRAD_MEH_DATA_DIR_RELATIVE = "../../../gruppe-adler/meh-data"
MARKDOWN_OUTPUT_FILE_RELATIVE = "../docs/index.md"
